$(eval $(call addlib_s,libprocfs,$(CONFIG_LIBPROCFS)))

LIBPROCFS_COMMON_INCLUDES-y      += -I$(LIBPROCFS_BASE)/include
CINCLUDES-$(CONFIG_LIBPROCFS)    += $(LIBPROCFS_COMMON_INCLUDES-y)
CXXINCLUDES-$(CONFIG_LIBPROCFS)    += $(LIBPROCFS_COMMON_INCLUDES-y)

LIBPROCFS_CFLAGS-$(call gcc_version_ge,8,0) += -Wno-cast-function-type

LIBPROCFS_SRCS-y += $(LIBPROCFS_BASE)/procfs_status.c

